service: voice-page
app: speakers
org: aflorithmic
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

plugins:
  - serverless-offline
  - serverless-bundle

functions:
  getParameters:
    handler: lambdas/getParameters.handler
    timeout: 30
    events:
      - http:
          path: /getParameters
          method: get
          cors: true
  getVoices:
    handler: lambdas/getVoices.handler
    timeout: 30
    events:
      - http:
          path: /getVoices
          method: post
          cors: true
